# Generated by Django 3.1.2 on 2020-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="curr_lat",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="curr_lon",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="latitude",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="longitude",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
