# Generated by Django 3.1.2 on 2020-10-18 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_profile',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='restaurant_profile',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant_profile',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant_profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_profile_pics'),
        ),
        migrations.AddField(
            model_name='restaurant_profile',
            name='state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_pics'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
