# Generated by Django 3.1.2 on 2020-11-25 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_choice', models.CharField(choices=[('chinese', 'Chinese'), ('mexican', 'Mexican'), ('italian', 'Italian')], default='chinese', max_length=16)),
                ('time_choice', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('coffee', 'Coffee & Tea'), ('drinks', 'Drinks')], default='breakfast', max_length=16)),
                ('budget_choice', models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$')], default='1', max_length=4)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upreferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
