# Generated by Django 3.1.2 on 2020-11-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0002_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
    ]
