# Generated by Django 3.1.2 on 2020-11-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0002_auto_20201115_1436"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_profile",
            name="curr_lat",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="curr_lon",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="longitude",
        ),
    ]
