# Generated by Django 3.1.2 on 2020-10-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0002_auto_20201018_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
