# Generated by Django 3.1.2 on 2020-11-08 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0002_user_profile_auth_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='auth_documents',
        ),
        migrations.CreateModel(
            name='ApprovalPendingUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_documents', models.FileField(upload_to='documents/pdfs/')),
                ('auth_status', models.CharField(choices=[('certified', 'Approve'), ('pending', 'Pending'), ('uncertified', 'Disapprove')], default='pending', max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
