# Generated by Django 3.1.2 on 2020-12-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0004_auto_20201206_1644"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant_profile",
            name="auth_status",
        ),
    ]
