# Generated by Django 3.1.2 on 2020-11-08 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0004_auto_20201108_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalpendingusers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='try_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
