# Generated by Django 3.1.2 on 2020-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0005_auto_20201108_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalpendingusers',
            name='auth_documents',
            field=models.FileField(default='documents/pdfs/test.pdf', upload_to='documents/pdfs/'),
        ),
    ]
