# Generated by Django 3.1.2 on 2020-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0006_restaurant_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
