# Generated by Django 3.1.2 on 2020-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_restaurant', '0007_auto_20201108_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalpendingusers',
            name='time_modified',
        ),
    ]
