# Generated by Django 3.1.2 on 2020-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0008_auto_20201027_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="business_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
