# Generated by Django 3.1.2 on 2020-11-02 20:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0009_auto_20201028_1114"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("review_context", models.TextField()),
                ("rating", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "level_entry_rating",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "wide_door_rating",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "accessible_table_rating",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "accessible_restroom_rating",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "accessible_path_rating",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relate_busid",
                        to="accessible_restaurant.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
