# Generated by Django 3.1.2 on 2020-11-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0011_auto_20201031_1557"),
        ("accessible_restaurant", "0010_auto_20201102_0119"),
    ]

    operations = []
