# Generated by Django 3.1.2 on 2020-11-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessible_restaurant", "0012_merge_20201102_2108"),
        ("accessible_restaurant", "0010_review"),
    ]

    operations = []
